;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-buffer
        helm-confirm-and-exit-minibuffer
        sp--cua-replace-region
        sp--self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        autopair-newline
        coffee-dedent-line-backspace
        cua-cut-region
        cua-delete-region
        other-window-or-split
        ruby-end-return
        ))
